# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/flow____/Linux_Unreal_Engine_5.1.1
GAMEPROJECTFILE =/home/flow____/Documents/Unreal Projects/Mini_Golf_In_Unreal/Mini_Golf_In_Unreal.uproject

TARGETS = \
	Mini_Golf_In_Unreal-Linux-DebugGame  \
	Mini_Golf_In_Unreal-Linux-Shipping  \
	Mini_Golf_In_Unreal \
	Mini_Golf_In_UnrealEditor-Linux-DebugGame  \
	Mini_Golf_In_UnrealEditor-Linux-Shipping  \
	Mini_Golf_In_UnrealEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Mini_Golf_In_UnrealEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Mini_Golf_In_UnrealEditor-Linux-Debug


Mini_Golf_In_Unreal-Linux-DebugGame:
	 $(PROJECTBUILD) Mini_Golf_In_Unreal Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Mini_Golf_In_Unreal-Linux-Shipping:
	 $(PROJECTBUILD) Mini_Golf_In_Unreal Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Mini_Golf_In_Unreal:
	 $(PROJECTBUILD) Mini_Golf_In_Unreal Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

Mini_Golf_In_UnrealEditor-Linux-DebugGame:
	 $(PROJECTBUILD) Mini_Golf_In_UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

Mini_Golf_In_UnrealEditor-Linux-Shipping:
	 $(PROJECTBUILD) Mini_Golf_In_UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

Mini_Golf_In_UnrealEditor:
	 $(PROJECTBUILD) Mini_Golf_In_UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
